package com.agenthub.application.orchestrator;

import com.agenthub.domain.agent.Agent;
import com.agenthub.domain.agent.BuiltInAgentIds;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Component;

@Component
public class PlannerPromptBuilder {

    public LayeredPlannerPrompt build(String userInput, Agent selectedAgent, List<Agent> mentionedAgents) {
        List<String> promptLayers = List.of(
                "baseCapability",
                "roleInstruction",
                "availableAgents",
                "conversationContext",
                "retrievedContext",
                "artifactHistory",
                "outputSchema",
                "fallbackPolicy");
        return new LayeredPlannerPrompt(
                buildSystemPrompt(),
                buildUserPrompt(userInput, selectedAgent, mentionedAgents),
                buildContextItems(selectedAgent, mentionedAgents),
                List.of(
                        "Artifact history: current demo task expects CODE, MARKDOWN, API_CONTRACT, REVIEW_REPORT.",
                        "Deploy preview and artifact revision are downstream operations and must not be generated by planner."),
                Map.of(
                        "plannerType", "LLM",
                        "schema", "OrchestratorPlan.v1",
                        "promptLayering", String.join(",", promptLayers),
                        "fallbackPolicy", "Fallback to RuleBasedPlanner on adapter fallback, timeout, invalid JSON, or schema failure."),
                promptLayers);
    }

    private String buildSystemPrompt() {
        return """
                [baseCapability]
                You are AgentHub's Orchestrator planner. Return only a plan. Do not generate code, files, deployment output, or Markdown fences.

                [roleInstruction]
                Act like a PM / PMO. Understand the user goal, split work into specialist Agent steps, define routing reasons, and preserve fallback safety.

                [availableAgents]
                Built-in roles are FRONTEND, BACKEND, REVIEWER. Custom selected Agent can replace the FRONTEND specialist.

                [conversationContext]
                Consider selectedAgent and leading @Agent mentions as explicit routing signals.

                [retrievedContext]
                Treat pinned context, MemoryItem, and Context Retrieval results as input context only. Do not invent hidden context.

                [artifactHistory]
                Existing Artifact history is for planning dependencies only. Do not mutate artifacts in the plan.

                [outputSchema]
                Return only valid JSON:
                {
                  "goal": "string",
                  "planningMode": "LLM_PLANNER",
                  "plannerReasoningSummary": "short string",
                  "acceptanceCriteria": ["string"],
                  "expectedArtifacts": ["CODE", "MARKDOWN", "API_CONTRACT", "REVIEW_REPORT"],
                  "parallelGroups": ["string"],
                  "steps": [
                    {
                      "stepOrder": 1,
                      "role": "FRONTEND",
                      "taskDescription": "string",
                      "requiredSkill": "string",
                      "parallelGroupKey": "string",
                      "dependsOnStepOrders": [1],
                      "routingReason": "string"
                    }
                  ]
                }
                Required roles: FRONTEND, BACKEND, REVIEWER.

                [fallbackPolicy]
                If unsure, keep the stable three-step plan. Invalid JSON or schema mismatch will fall back to RuleBasedPlanner.
                """;
    }

    private String buildUserPrompt(String userInput, Agent selectedAgent, List<Agent> mentionedAgents) {
        return """
                [conversationContext]
                User input:
                %s

                Selected agent:
                %s

                Mentioned agents:
                %s

                [planningInstruction]
                Build a safe AgentHub demo plan with exactly three specialist roles:
                FRONTEND, BACKEND, REVIEWER.
                If multiple agents are mentioned, place FRONTEND and REVIEWER in MENTIONED_AGENT_GROUP.
                Backend should depend on frontend unless the plan has a clear reason otherwise.
                """.formatted(
                userInput == null ? "" : userInput,
                selectedAgent == null ? "none" : selectedAgent.getName() + " / " + selectedAgent.getId().value(),
                mentionedAgents == null || mentionedAgents.isEmpty()
                        ? "none"
                        : mentionedAgents.stream()
                                .map(agent -> agent.getName() + " / " + agent.getId().value())
                                .toList());
    }

    private List<String> buildContextItems(Agent selectedAgent, List<Agent> mentionedAgents) {
        List<String> contextItems = new ArrayList<>();
        contextItems.add("Prompt layer: baseCapability=plan-only, no code generation.");
        contextItems.add("Prompt layer: roleInstruction=PM / PMO task split and route.");
        contextItems.add("Prompt layer: availableAgents includes " + BuiltInAgentIds.FRONTEND_BUILDER
                + ", " + BuiltInAgentIds.BACKEND_WORKER + ", " + BuiltInAgentIds.REVIEWER + ".");
        contextItems.add("Prompt layer: fallbackPolicy requires RuleBasedPlanner fallback on schema failure.");
        contextItems.add("Default adapters: FRONTEND=CODEX, BACKEND=MOCK, REVIEWER=CLAUDE_CODE.");
        if (selectedAgent != null) {
            contextItems.add("Selected agent should replace the frontend specialist: " + selectedAgent.getName());
        }
        if (mentionedAgents != null && !mentionedAgents.isEmpty()) {
            contextItems.add("Mentioned agents count: " + mentionedAgents.size());
        }
        return contextItems;
    }

    public record LayeredPlannerPrompt(
            String systemPrompt,
            String userPrompt,
            List<String> contextItems,
            List<String> artifactSummaries,
            Map<String, Object> metadata,
            List<String> layers) {
    }
}
