import { getIdValue } from "../../utils/id";
import type { Artifact } from "./artifactTypes";

export interface VersionHistoryEntry {
  artifact: Artifact;
  artifactId: string;
  parentArtifact: Artifact | null;
  basedOnVersionLabel: string | null;
  isRevision: boolean;
}

export interface DiffSummary {
  instruction: string | null;
  basedOnLabel: string | null;
  summary: string;
  changedItems: string[];
  notChanged: string[];
  risk: string;
  isInitialVersion: boolean;
}

function toTimestamp(value: string): number {
  const parsed = Date.parse(value);
  return Number.isNaN(parsed) ? 0 : parsed;
}

function resolveParentArtifact(artifacts: Artifact[], artifact: Artifact): Artifact | null {
  if (!artifact.parentArtifactId) {
    return null;
  }

  return artifacts.find((candidate) => getIdValue(candidate.id) === artifact.parentArtifactId) ?? null;
}

function resolveRootArtifactId(artifacts: Artifact[], artifact: Artifact): string {
  let current = artifact;
  let guard = 0;

  while (current.parentArtifactId && guard < 20) {
    const parent = resolveParentArtifact(artifacts, current);

    if (!parent) {
      return current.parentArtifactId;
    }

    current = parent;
    guard += 1;
  }

  return getIdValue(current.id);
}

export function isRevisionArtifact(artifact: Artifact): boolean {
  return Boolean(artifact.parentArtifactId || artifact.revisionInstruction);
}

export function getVersionHistoryEntries(
  artifacts: Artifact[],
  selectedArtifact: Artifact | null
): VersionHistoryEntry[] {
  if (!selectedArtifact) {
    return [];
  }

  const selectedRootId = resolveRootArtifactId(artifacts, selectedArtifact);

  return artifacts
    .filter((artifact) => artifact.title === selectedArtifact.title)
    .filter((artifact) => {
      if (!isRevisionArtifact(artifact) && !isRevisionArtifact(selectedArtifact)) {
        return true;
      }

      const artifactRootId = resolveRootArtifactId(artifacts, artifact);
      return artifactRootId === selectedRootId || getIdValue(artifact.id) === selectedRootId;
    })
    .sort((left, right) => {
      if (left.version !== right.version) {
        return left.version - right.version;
      }

      return toTimestamp(left.createdAt) - toTimestamp(right.createdAt);
    })
    .map((artifact) => {
      const parentArtifact = resolveParentArtifact(artifacts, artifact);

      return {
        artifact,
        artifactId: getIdValue(artifact.id),
        parentArtifact,
        basedOnVersionLabel: parentArtifact ? `v${parentArtifact.version}` : null,
        isRevision: isRevisionArtifact(artifact)
      };
    });
}

export function buildDiffSummary(artifacts: Artifact[], artifact: Artifact): DiffSummary {
  const parentArtifact = resolveParentArtifact(artifacts, artifact);
  const instruction = artifact.revisionInstruction?.trim() || null;
  const basedOnLabel = parentArtifact ? `${parentArtifact.title} v${parentArtifact.version}` : null;

  if (!instruction) {
    return {
      instruction: null,
      basedOnLabel,
      summary: "This artifact is the initial version. No revision summary available.",
      changedItems: [],
      notChanged: [],
      risk: "This is a static demo artifact. No real diff analysis was performed.",
      isInitialVersion: true
    };
  }

  const mentionsBlue = instruction.includes("蓝") || instruction.toLowerCase().includes("blue");
  const mentionsLoading =
    instruction.includes("loading") || instruction.includes("加载") || instruction.includes("等待");

  const changedItems = [
    mentionsBlue ? "Button style changed to blue." : "Primary action style updated.",
    mentionsLoading
      ? "Loading state added to prevent duplicate submission."
      : "Interaction state updated for the primary action.",
    mentionsLoading
      ? "Button text changes while loading."
      : "Artifact copy was adjusted to reflect the revision request."
  ];

  return {
    instruction,
    basedOnLabel,
    summary:
      "This revision is a static artifact-centered iteration based on the previous version and the user's follow-up instruction.",
    changedItems,
    notChanged: [
      "Email input remains unchanged.",
      "Verification code input remains unchanged.",
      "Component structure remains simple for preview."
    ],
    risk: "This is a static demo revision, not generated by real code analysis.",
    isInitialVersion: false
  };
}
